apiVersion: v1
kind: Pod
metadata:
  name: staticbusybox
  namespace: sooraj
spec:
  containers:
  - name: busybox-container
    image: busybox
    command:
      - sleep
      - "1000"
    ports:
    - containerPort: 80
